extends Node

const BULLET_DAMAGE = 10
const BULLET_SPEED = 800
const BULLET_FIRE_RATE = 0.25
const BULLET_FIRE_RATE_VARIANCE = 0.10

const STATION_MANAGER_ECONOMY_INITIAL_AMOUNT = 0
const STATION_MANAGER_MISSILE_INITIAL_AMOUNT = 8
const STATION_MANAGER_LASER_INITIAL_AMOUNT = 8
const STATION_MANAGER_SHIELD_INITIAL_AMOUNT = 0
const STATION_MANAGER_WINGS_INITIAL_AMOUNT = 8

const PLAYER_SCRAP_DEFAULT_DEPOSIT_AMOUNT = 1
const PLAYER_MISSILE_INITIAL_AMOUNT = 0
const PLAYER_LASER_INITIAL_AMOUNT = 0
const PLAYER_SHIELD_INITIAL_AMOUNT = 0
const PLAYER_WINGS_INITIAL_AMOUNT = 0

const POWER_UP_SCRAP_AMOUNT_FOR_MISSILE = 4
const POWER_UP_SCRAP_AMOUNT_FOR_LASER = 4
const POWER_UP_SCRAP_AMOUNT_FOR_SHIELD = 4
const POWER_UP_SCRAP_AMOUNT_FOR_WINGS = 4

# Base stats for battleship
var BATTLESHIP_MAX_HP = 400
var BATTLESHIP_BASE_ATTACK = 20
const BATTLESHIP_BASE_ACCURACY = 100
const BATTLESHIP_BASE_EVASION = 5

# HP and attack scale by a factor of <x> per level
const BATTLESHIP_MAX_HP_SCALING = 1.2
const BATTLESHIP_BASE_ATTACK_SCALING = 1.1
# Accuracy and evasion scale in additive manner per level
const BATTLESHIP_BASE_ACCURACY_SCALING = 5
const BATTLESHIP_BASE_EVASION_SCALING = 2.5

const BULLET_DAMAGE_MULTIPLIER = 0.5
const BULLET_ACCURACY_MULTIPLIER = 0.8
var BULLET_DAMAGE = BATTLESHIP_BASE_ATTACK * BULLET_DAMAGE_MULTIPLIER
var BULLET_ACCURACY = BATTLESHIP_BASE_ACCURACY * BULLET_ACCURACY_MULTIPLIER
const BULLET_SPEED = 800
const BULLET_FIRE_RATE = 0.25
const BULLET_FIRE_RATE_VARIANCE = 0.10

const MISSILE_DAMAGE_MULTIPLIER = 0.8
const MISSILE_ACCURACY_MULTIPLIER = 10
var MISSILE_DAMAGE = BATTLESHIP_BASE_ATTACK * MISSILE_DAMAGE_MULTIPLIER
var MISSILE_ACCURACY = BATTLESHIP_BASE_ACCURACY * MISSILE_ACCURACY_MULTIPLIER
const MISSILE_SPEED = 200
const MISSILE_FIRE_RATE = 1
const MISSILE_FIRE_RATE_VARIANCE = 0.5

const LASER_DAMAGE_MULTIPLIER = 1.2
const LASER_ACCURACY_MULTIPLIER = 0.5
var LASER_DAMAGE = BATTLESHIP_BASE_ATTACK * LASER_DAMAGE_MULTIPLIER
var LASER_ACCURACY = BATTLESHIP_BASE_ACCURACY * LASER_ACCURACY_MULTIPLIER
const LASER_SPEED = 125
const LASER_FIRE_RATE = 3
const LASER_FIRE_RATE_VARIANCE = 0.5

# Percentage of hp the shield covers and how much it increments per level (additive)
var SHIELD_COVERAGE = 0.2
const SHIELD_COVERAGE_PER_LEVEL = 0.1

# Extra evasion provided by wings and how much it increments per level (additive)
var WINGS_BONUS_EVASION = 20
const WINGS_BONUS_EVASION_PER_LEVEL = 10

const MULTIPLIER_BULLET_TO_SHIP = 1.0
const MULTIPLIER_BULLET_TO_SHIELD = 0.5
const MULTIPLIER_MISSILE_TO_SHIP = 1.2
const MULTIPLIER_MISSILE_TO_SHIELD = 0.2
const MULTIPLIER_LASER_TO_SHIP = 1.4
const MULTIPLIER_LASER_TO_SHIELD = 3

func level_up():
	BATTLESHIP_MAX_HP *= BATTLESHIP_MAX_HP_SCALING
	BATTLESHIP_BASE_ATTACK *= BATTLESHIP_BASE_ATTACK_SCALING
	BATTLESHIP_BASE_ACCURACY += BATTLESHIP_BASE_ACCURACY_SCALING
	BATTLESHIP_BASE_EVASION += BATTLESHIP_BASE_EVASION_SCALING
	
	SHIELD_COVERAGE += SHIELD_COVERAGE_PER_LEVEL
	WINGS_BONUS_EVASION += WINGS_BONUS_EVASION_PER_LEVEL
	
	update()

func update():
	BULLET_DAMAGE = BATTLESHIP_BASE_ATTACK * BULLET_DAMAGE_MULTIPLIER
	BULLET_ACCURACY = BATTLESHIP_BASE_ACCURACY * BULLET_ACCURACY_MULTIPLIER
	
	MISSILE_DAMAGE = BATTLESHIP_BASE_ATTACK * MISSILE_DAMAGE_MULTIPLIER
	MISSILE_ACCURACY = BATTLESHIP_BASE_ACCURACY * MISSILE_ACCURACY_MULTIPLIER
	
	LASER_DAMAGE = BATTLESHIP_BASE_ATTACK * LASER_DAMAGE_MULTIPLIER
	LASER_ACCURACY = BATTLESHIP_BASE_ACCURACY * LASER_ACCURACY_MULTIPLIER
