extends Node

const BULLET_DAMAGE = 10
const BULLET_SPEED = 800
const BULLET_FIRE_RATE = 0.25
const BULLET_FIRE_RATE_VARIANCE = 0.10

const ECONOMY_INITIAL_AMOUNT = 0

const SCRAP_TYPE_MISSILE_INITIAL_AMOUNT = 0
const SCRAP_TYPE_LASER_INITIAL_AMOUNT = 0
const SCRAP_TYPE_SHIELD_INITIAL_AMOUNT = 0
const SCRAP_TYPE_WINGS_INITIAL_AMOUNT = 0

const BATTLESHIP_MAX_HP = 400
const BATTLESHIP_BASE_ATTACK = 20
const BATTLESHIP_BASE_ACCURACY = 100
const BATTLESHIP_BASE_EVASION = 5

const BULLET_DAMAGE_MULTIPLIER = 0.5
const BULLET_ACCURACY_MULTIPLIER = 0.8
const BULLET_DAMAGE = BATTLESHIP_BASE_ATTACK * BULLET_DAMAGE_MULTIPLIER
const BULLET_ACCURACY = BATTLESHIP_BASE_ACCURACY * BULLET_ACCURACY_MULTIPLIER
const BULLET_SPEED = 800
const BULLET_FIRE_RATE = 0.25
const BULLET_FIRE_RATE_VARIANCE = 0.10

const MISSILE_DAMAGE_MULTIPLIER = 0.8
const MISSILE_ACCURACY_MULTIPLIER = 10
const MISSILE_DAMAGE = BATTLESHIP_BASE_ATTACK * MISSILE_DAMAGE_MULTIPLIER
const MISSILE_ACCURACY = BATTLESHIP_BASE_ACCURACY * MISSILE_ACCURACY_MULTIPLIER
const MISSILE_SPEED = 200
const MISSILE_FIRE_RATE = 1
const MISSILE_FIRE_RATE_VARIANCE = 0.5

const LASER_DAMAGE_MULTIPLIER = 1.2
const LASER_ACCURACY_MULTIPLER = 0.9
const LASER_DAMAGE = BATTLESHIP_BASE_ATTACK * LASER_DAMAGE_MULTIPLIER
const LASER_ACCURACY = BATTLESHIP_BASE_ACCURACY * LASER_ACCURACY_MULTIPLER
const LASER_SPEED = 125
const LASER_FIRE_RATE = 3
const LASER_FIRE_RATE_VARIANCE = 0.5

const MULTIPLIER_BULLET_TO_SHIP = 1.0
const MULTIPLIER_BULLET_TO_SHIELD = 0.5
const MULTIPLIER_MISSILE_TO_SHIP = 1.2
const MULTIPLIER_MISSILE_TO_SHIELD = 0.75
